In [81]:
import pandas as pd
import numpy as np

In [82]:
data1=pd.read_csv("deepsolar_t.csv",sep=",")
data1

tile_count  solar_system_count  total_panel_area         fips  \
0              0                   0          0.000000  27145011200   
1             25                  21       1133.436461  27145011301   
2              3                   3         64.505776  27145011302   
3              0                   0          0.000000  27145011304   
4              5                   5        164.583303  27145011400   
5              0                   0          0.000000  27145011500   
6              2                   2         25.299013  27145011600   
7              0                   0          0.000000  27145010500   
8              0                   0          0.000000  27145011100   
9             11                  10        415.365350  27145010102   
10            16                  15        532.693616  27145000500   
11             2                   2         26.260940  27145000801   
12             3                   3         55.673595  27145001001   
13             0                   0          0.000000  27145010200   
14            55                   4       4314.757421  27145010401   
15             1                   1         30.538029  27145000601   
16             4                   2        328.877680  27145010600   
17             0                   0          0.000000  27145010900   
18            28                   3       3972.844268  27145011000   
19             1                   1          3.906284  27145000301   
20             2                   2         45.662388  27145000302   
21             6                   2        268.124309  27145000401   
22            10                  10        219.445054  27145000402   
23             6                   3        191.224200  27145000602   
24            21                  18        557.623643  27145000701   
25             3                   3         35.394311  27145000901   
26             4                   4         54.008072  27145010101   
27             0                   0          0.000000  27145010402   
28             6                   2        446.878949  27145010403   
29            10                   8        264.512905  36071014400   
...          ...                 ...               ...          ...   
6029          66                  44       1303.875055  25005640300   
6030          38                  27        930.108481  25005640400   
6031           3                   3         63.781079  25005640901   
6032          12                   4        397.261781  25005641000   
6033          78                  14       6703.541588  25005641200   
6034           0                   0          0.000000  25005630102   
6035          95                  59       2092.104039  25005641700   
6036           7                   5        220.002281  25005641900   
6037          14                   6        736.446276  25005642000   
6038          25                  18        748.869738  25005642300   
6039           9                   7        124.028118  25005630300   
6040          55                  15       5117.570417  25005630400   
6041           7                   5        268.928341  25005641400   
6042          92                  71       2127.355820  25005645101   
6043         134                  96       2877.233789  25005645102   
6044           7                   7        243.074031  25005652700   
6045           9                   7        140.147832  25005641500   
6046          49                  21       3646.711670  25005650400   
6047         259                 111      16664.845210  25005653101   
6048          31                  25        975.962750  25005650300   
6049          89                  66       2097.530005  25005653203   
6050          18                  14        455.356095  25005653204   
6051          54                  26       3281.439054  25005641600   
6052         154                 119       4022.002706  25005650101   
6053          65              

In [83]:
# statistika deskriptif
data1.describe()

tile_count  solar_system_count  total_panel_area          fips  \
count  6059.000000         6059.000000       6059.000000  6.059000e+03   
mean     33.904605           24.034659       1391.913220  1.797246e+10   
std      65.841204           42.032417       5076.066337  1.513903e+10   
min       0.000000            0.000000          0.000000  5.009790e+09   
25%       2.000000            2.000000         55.989921  6.037504e+09   
50%      12.000000            9.000000        345.941816  1.201103e+10   
75%      38.000000           27.000000       1213.049644  3.604700e+10   
max    1623.000000          790.000000     216732.195600  5.502599e+10   

       average_household_income  education_bachelor  education_college  \
count               5975.000000         6059.000000        6059.000000   
mean               77754.516717          573.811850         773.236343   
std                44415.257077          445.587277         459.348441   
min                 7782.807018            0.000000           0.000000   
25%                49796.898455          233.000000         441.000000   
50%                66948.148150          471.000000         695.000000   
75%                92180.782165          809.000000        1024.000000   
max               537130.215800         5440.000000        6791.000000   

       education_doctoral  education_high_school_graduate  \
count         6059.000000                     6059.000000   
mean            38.875557                      701.046707   
std             62.343935                      421.755742   
min              0.000000                        0.000000   
25%              0.000000                      407.000000   
50%             17.000000                      639.000000   
75%             48.000000                      917.000000   
max            877.000000                     3487.000000   

       education_less_than_high_school             ...               \
count                      6059.000000             ...                
mean                        529.060241             ...                
std                         463.185248             ...                
min                           0.000000             ...                
25%                         175.000000             ...                
50%                         389.000000             ...                
75%                         771.000000             ...                
max                        3250.000000             ...                

       incentive_count_nonresidential  incentive_residential_state_level  \
count                     6059.000000                        6059.000000   
mean                        55.547615                          11.317379   
std                         25.895220                           5.082493   
min                         16.000000                           2.000000   
25%                         31.000000                           6.000000   
50%                         54.000000                          15.000000   
75%                         85.000000                          15.000000   
max                         85.000000                          17.000000   

       incentive_nonresidential_state_level  net_metering  feedin_tariff  \
count                           6059.000000   6059.000000    6059.000000   
mean                              12.555867     16.646641       3.741211   
std                                4.350291      7.920979       4.440841   
min                                4.000000      0.000000       0.000000   
25%                                8.000000      9.000000       0.000000   
50%                               16.000000     20.000000       0.000000   
75%                               16.000000     21.000000       9.000000   
max                               17.000000     35.000000      11.000000   

       cooperate_tax  property_tax    sales_tax       rebate  \
count         6059.0   6059.000000  6059.000000  6

In [84]:
#missing value
np.sum(data1.isnull())

tile_count                                 0
solar_system_count                         0
total_panel_area                           0
fips                                       0
average_household_income                  84
county                                     0
education_bachelor                         0
education_college                          0
education_doctoral                         0
education_high_school_graduate             0
education_less_than_high_school            0
education_master                           0
education_population                       0
education_professional_school              0
employed                                   0
gini_index                                80
heating_fuel_coal_coke                     0
heating_fuel_electricity                   0
heating_fuel_fuel_oil_kerosene             0
heating_fuel_gas                           0
heating_fuel_housing_unit_count            0
heating_fuel_none                          0
heating_fu

In [85]:
#imputasi untuk missing value
data1['average_household_income']=data1['average_household_income'].fillna((data1['average_household_income'].mean()))
data1['gini_index']=data1['gini_index'].fillna((data1['gini_index'].mean()))
data1['land_area']=data1['land_area'].fillna((data1['land_area'].mean()))
data1['per_capita_income']=data1['per_capita_income'].fillna((data1['per_capita_income'].mean()))
data1['population_density']=data1['population_density'].fillna((data1['population_density'].mean()))
data1['travel_time_less_than_10_rate']=data1['travel_time_less_than_10_rate'].fillna((data1['travel_time_60_89_rate'].mean()))
data1['travel_time_10_19_rate']=data1['travel_time_10_19_rate'].fillna((data1['travel_time_10_19_rate'].mean()))
data1['travel_time_20_29_rate']=data1['travel_time_20_29_rate'].fillna((data1['travel_time_20_29_rate'].mean()))
data1['travel_time_30_39_rate']=data1['travel_time_30_39_rate'].fillna((data1['travel_time_30_39_rate'].mean()))
data1['travel_time_40_59_rate']=data1['travel_time_40_59_rate'].fillna((data1['travel_time_40_59_rate'].mean()))
data1['travel_time_60_89_rate']=data1['travel_time_60_89_rate'].fillna((data1['travel_time_60_89_rate'].mean()))
data1['health_insurance_public_rate']=data1['health_insurance_public_rate'].fillna((data1['health_insurance_public_rate'].mean()))
data1['health_insurance_none_rate']=data1['health_insurance_none_rate'].fillna((data1['health_insurance_none_rate'].mean()))
data1['age_median']=data1['age_median'].fillna((data1['age_median'].mean()))
data1['travel_time_average']=data1['travel_time_average'].fillna((data1['travel_time_average'].mean()))
data1['voting_2012_dem_percentage']=data1['voting_2012_dem_percentage'].fillna((data1['voting_2012_dem_percentage'].mean()))
data1['voting_2012_gop_percentage']=data1['voting_2012_gop_percentage'].fillna((data1['voting_2012_gop_percentage'].mean()))
data1['number_of_years_of_education']=data1['number_of_years_of_education'].fillna((data1['number_of_years_of_education'].mean()))
data1['diversity']=data1['diversity'].fillna((data1['diversity'].mean()))
data1['number_of_solar_system_per_household']=data1['number_of_solar_system_per_household'].fillna((data1['number_of_solar_system_per_household'].mean()))
np.sum(data1.isnull())

tile_count                              0
solar_system_count                      0
total_panel_area                        0
fips                                    0
average_household_income                0
county                                  0
education_bachelor                      0
education_college                       0
education_doctoral                      0
education_high_school_graduate          0
education_less_than_high_school         0
education_master                        0
education_population                    0
education_professional_school           0
employed                                0
gini_index                              0
heating_fuel_coal_coke                  0
heating_fuel_electricity                0
heating_fuel_fuel_oil_kerosene          0
heating_fuel_gas                        0
heating_fuel_housing_unit_count         0
heating_fuel_none                       0
heating_fuel_other                      0
heating_fuel_solar                

In [86]:
from scipy import stats
deepsolar=data1.drop(['county', 'voting_2016_dem_win', 'voting_2012_dem_win', 'state'], 1)
z = np.abs(stats.zscore(deepsolar._get_numeric_data()))
print(z)
data1=data1[(z<3).all(axis=1)]
print(data1.shape)

[[0.51498759 0.57185963 0.27423363 ... 0.6088072  1.11219413 1.28005525]
 [0.13525481 0.07220402 0.05092488 ... 0.6088072  1.11219413 1.28005525]
 [0.46941965 0.50048026 0.26152475 ... 0.6088072  1.11219413 1.28005525]
 ...
 [1.24697249 1.11745219 1.43799047 ... 3.69859295 1.11219413 1.0279347 ]
 [0.16563343 0.09599715 0.16095671 ... 3.69859295 1.11219413 1.0279347 ]
 [0.07739554 0.16737652 0.41625094 ... 3.69859295 1.11219413 1.0279347 ]]
(0, 168)


C:\Users\myacer\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in less
  """
